// frontend/src/components/AppSidebar.vue
<script setup lang="ts">
import NavMain from "@/components/NavMain.vue";

import NavSecondary from "@/components/NavSecondary.vue";
import {
  Sidebar,
  SidebarContent,
  SidebarFooter,
  SidebarHeader,
  type SidebarProps,
} from "@/components/ui/sidebar";
import { BookOpen, LifeBuoy, Network, Send, Settings } from "lucide-vue-next";

const props = withDefaults(defineProps<SidebarProps>(), {
  variant: "inset",
});

const data = {
  navMain: [
    {
      title: "Network",
      url: "#",
      icon: Network,
      isActive: true,
      items: [
        {
          title: "IPCC",
          url: "/ipcc",
        },
        {
          title: "APN",
          url: "/apn",
        },
      ],
    },
  ],
  navSecondary: [
    {
      title: "Settings",
      url: "/settings",
      icon: Settings,
    },
    {
      title: "Documentation",
      url: "/documentation",
      icon: BookOpen,
    },
    {
      title: "Support",
      url: "/support",
      icon: LifeBuoy,
    },
    {
      title: "Feedback",
      url: "/feedback",
      icon: Send,
    },
  ],
};
</script>

<template>
  <Sidebar v-bind="props">
    <SidebarHeader>
      <Label
        className="data-[state=open]:bg-sidebar-accent data-[state=open]:text-sidebar-accent-foreground"
      >
        <BookOpen />
        OpenTools
      </Label>
    </SidebarHeader>
    <SidebarContent>
      <NavMain :items="data.navMain" />
    </SidebarContent>
    <SidebarFooter>
      <NavSecondary :items="data.navSecondary" class="mt-auto" />
    </SidebarFooter>
  </Sidebar>
</template>

// frontend/src/lib/components/app-sidebar.svelte
<script lang="ts" module>
	import BookOpen from '@lucide/svelte/icons/book-open';
	import LifeBuoy from '@lucide/svelte/icons/life-buoy';
	import Send from '@lucide/svelte/icons/send';
	import Settings2 from '@lucide/svelte/icons/settings-2';
	import Network from '@lucide/svelte/icons/network';

	const data = {
		navMain: [
			{
				title: 'Network',
				url: '/network',
				icon: Network,
				isActive: true,
				items: [
					{
						title: 'IPCC',
						url: '/network/ipcc'
					},
					{
						title: 'APN',
						url: '/network/apn'
					}
				]
			}
		],
		navSecondary: [
			{
				title: 'Settings',
				url: '/settings',
				icon: Settings2
			},
			{
				title: 'Documentation',
				url: '/docs',
				icon: BookOpen
			},
			{
				title: 'Support',
				url: '/support',
				icon: LifeBuoy
			},
			{
				title: 'Feedback',
				url: '/feedback',
				icon: Send
			}
		]
	};
</script>

<script lang="ts">
	import NavMain from '$lib/components/nav-main.svelte';
	import NavSecondary from '$lib/components/nav-secondary.svelte';
	import * as Sidebar from '$lib/components/ui/sidebar/index.js';
	import type { ComponentProps } from 'svelte';

	let { ref = $bindable(null), ...restProps }: ComponentProps<typeof Sidebar.Root> = $props();
</script>

<Sidebar.Root bind:ref variant="inset" collapsible="icon" {...restProps}>
	<Sidebar.Header>OpeniTools</Sidebar.Header>
	<Sidebar.Content>
		<NavMain items={data.navMain} />
	</Sidebar.Content>
	<Sidebar.Footer>
		<NavSecondary items={data.navSecondary} class="mt-auto" />
	</Sidebar.Footer>
</Sidebar.Root>
